import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5101/',{waitUntil:'networkidle'});
assert.equal(await page.locator('.dh-hero').count(),1);
assert.equal(await page.locator('footer').count(),1);
assert.equal(await page.locator('.seo-hero').count(),0);
await page.screenshot({path:'artifacts/restored-home-desktop.png',fullPage:true});
await page.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('link',{name:'SEO & Digital'}).click();
await page.waitForURL('**/seo-digital-marketing');
await page.locator('.seo-hero').waitFor();
assert.equal(await page.locator('footer').count(),0);
await page.reload();await page.locator('.seo-hero').waitFor();
await page.getByRole('link',{name:'XPATZHUB home'}).click();
await page.locator('.dh-hero').waitFor();
await page.setViewportSize({width:390,height:844});
await page.getByRole('button',{name:'Open navigation'}).click();
await page.getByRole('navigation',{name:'Mobile navigation',exact:true}).getByRole('link',{name:/SEO & Digital/}).click();
await page.waitForURL('**/seo-digital-marketing');await page.locator('.seo-hero').waitFor();
await page.goBack();await page.getByRole('button',{name:'Open navigation'}).waitFor();
assert.equal(await page.locator('footer').count(),1);
assert.deepEqual(errors,[]);
console.log('PASS: restored homepage/footer; desktop and mobile SEO navigation; direct route reload; logo return home; browser back; no runtime errors.');
await browser.close();
