export const communityFaqData = [
  {
    id: 'comm-faq-01',
    number: '01',
    question: 'How can my brand work with the XPATZHUB community?',
    answer: 'XPATZHUB helps brands connect with relevant audiences through community campaigns, partnerships, activations, events and other community-led opportunities. We shape the approach around your brand, audience and campaign objectives.',
    paperType: 'cream', // warm cream paper
    rotation: -0.6,
    hasTape: true,
    tapeSide: 'left',
    handwrittenSignoff: "Let's make it happen.",
  },
  {
    id: 'comm-faq-02',
    number: '02',
    question: 'What types of community marketing campaigns do you offer?',
    answer: 'Campaigns can include community promotions, brand collaborations, strategic partnerships, on-ground activations, events, meetups and other initiatives designed to create meaningful interaction between brands and people.',
    paperType: 'charcoal', // subtle dark textured charcoal paper
    rotation: 0.5,
    hasTape: false,
    handwrittenSignoff: null,
  },
  {
    id: 'comm-faq-03',
    number: '03',
    question: 'Who is the XPATZHUB community?',
    answer: 'XPATZHUB connects with a diverse expat audience across the UAE, bringing together people from different backgrounds, interests and communities while creating relevant opportunities for brands to participate authentically.',
    paperType: 'beige', // soft beige / muted kraft
    rotation: -0.4,
    hasTape: true,
    tapeSide: 'right',
    handwrittenSignoff: 'Good to know.',
  },
  {
    id: 'comm-faq-04',
    number: '04',
    question: 'Can you target specific audiences or communities?',
    answer: 'Yes. Community campaigns can be shaped around factors such as campaign objectives, interests, locations and relevant audience groups to help brands connect with people who are more likely to engage with their message.',
    paperType: 'cream',
    rotation: 0.6,
    hasTape: false,
    handwrittenSignoff: null,
  },
  {
    id: 'comm-faq-05',
    number: '05',
    question: 'Do you organise on-ground brand activations?',
    answer: 'Yes. XPATZHUB can support on-ground activations that bring brands directly into real community environments through interactive experiences, promotions, launches and other engagement opportunities.',
    paperType: 'charcoal',
    rotation: -0.5,
    hasTape: true,
    tapeSide: 'left',
    handwrittenSignoff: 'Real impact starts here.',
  },
  {
    id: 'comm-faq-06',
    number: '06',
    question: 'Can XPATZHUB help with events and community meetups?',
    answer: 'Yes. Community-led events and meetups can be used to create genuine conversations, networking opportunities, brand experiences and stronger relationships between businesses and their audiences.',
    paperType: 'beige',
    rotation: 0.4,
    hasTape: false,
    handwrittenSignoff: null,
  },
  {
    id: 'comm-faq-07',
    number: '07',
    question: 'Can brands collaborate with XPATZHUB for product promotions?',
    answer: 'Yes. Depending on the brand and campaign, we can explore community-led product promotions, collaborations and experiences designed to introduce products to relevant audiences in an authentic way.',
    paperType: 'cream',
    rotation: -0.5,
    hasTape: false,
    handwrittenSignoff: null,
  },
  {
    id: 'comm-faq-08',
    number: '08',
    question: 'Is community marketing suitable for small businesses?',
    answer: 'Yes. Community marketing can be adapted for businesses at different stages of growth. The campaign approach can be shaped around your objectives, target audience and available scope rather than using the same solution for every brand.',
    paperType: 'charcoal',
    rotation: 0.5,
    hasTape: true,
    tapeSide: 'right',
    handwrittenSignoff: 'Good to know.',
  },
  {
    id: 'comm-faq-09',
    number: '09',
    question: 'Do you work with brands across the UAE?',
    answer: 'Yes. XPATZHUB works with businesses and communities across the UAE, with campaigns and activations adapted around relevant locations, audiences and opportunities.',
    paperType: 'beige',
    rotation: -0.4,
    hasTape: false,
    handwrittenSignoff: null,
  },
  {
    id: 'comm-faq-10',
    number: '10',
    question: 'How do we start a community campaign with XPATZHUB?',
    answer: 'Start by sharing your brand, audience and campaign goals with us. From there, we can identify suitable community opportunities and develop an approach designed around the connections and outcomes you want to create.',
    paperType: 'cream',
    rotation: 0.6,
    hasTape: true,
    tapeSide: 'left',
    handwrittenSignoff: "Let's make it happen.",
  },
];

export const communityFaqSchemaData = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: communityFaqData.map((item) => ({
    '@type': 'Question',
    name: item.question,
    acceptedAnswer: {
      '@type': 'Answer',
      text: item.answer,
    },
  })),
};
